### ISSUE TITLE
Need function for write characteristic no response or example how to do it

### ISSUE THREAD

**Issue by dwmoffatt** [b3b/able#17]
I see that there is a function in BLE.java but not sure how to access it in able as I dont see a function for it.

**Comment by b3b** [comment]
Since characteristics  are pyjnius reflections of BluetoothGattCharacteristic Java objects (https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic), it is possible to call:
```python 
characteristic.setWriteType(1)  #  WRITE_TYPE_NO_RESPONSE = 1
````
before the `ble.write_characteristic(characteristic, '...')`

Or, more clearly:

```python
from jnius import autoclass
BluetoothGattCharacteristic = autoclass('android.bluetooth.BluetoothGattCharacteristic')
characteristic.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE)
ble.write_characteristic(characteristic, '...')
```

Currently, `writeCharacteristicNoResponse` is not exposed from BLE.java. I think this method is redundant, and should be just deleted.

**Comment by dwmoffatt** [comment]
Thank you for the example! Going to try it right now!

**Comment by dwmoffatt** [comment]
Worked! This library is awesome by the way!

**Comment by b3b** [comment]
Added a new option for convenience:

```python
from able import WriteType
ble.write_characteristic(characteristic, '...', write_type=WriteType.NO_RESPONSE)
```
